# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/inference.InferenceService/LoadModel',
                request_serializer=inference__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=inference__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/inference.InferenceService/UnloadModel',
                request_serializer=inference__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=inference__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/inference.InferenceService/ListModels',
                request_serializer=inference__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=inference__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.ListModelRegistry = channel.unary_unary(
                '/inference.InferenceService/ListModelRegistry',
                request_serializer=inference__pb2.ListModelRegistryRequest.SerializeToString,
                response_deserializer=inference__pb2.ListModelRegistryResponse.FromString,
                _registered_method=True)
        self.EvictModelRegistryEntry = channel.unary_unary(
                '/inference.InferenceService/EvictModelRegistryEntry',
                request_serializer=inference__pb2.EvictModelRegistryRequest.SerializeToString,
                response_deserializer=inference__pb2.EvictModelRegistryResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/inference.InferenceService/Predict',
                request_serializer=inference__pb2.PredictRequest.SerializeToString,
                response_deserializer=inference__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.StreamPredict = channel.stream_stream(
                '/inference.InferenceService/StreamPredict',
                request_serializer=inference__pb2.StreamPredictRequest.SerializeToString,
                response_deserializer=inference__pb2.StreamPredictResponse.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/inference.InferenceService/OpenSession',
                request_serializer=inference__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/inference.InferenceService/CloseSession',
                request_serializer=inference__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/inference.InferenceService/CancelSession',
                request_serializer=inference__pb2.CancelSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.CancelSessionResponse.FromString,
                _registered_method=True)
        self.Capabilities = channel.unary_unary(
                '/inference.InferenceService/Capabilities',
                request_serializer=inference__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=inference__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/inference.InferenceService/Health',
                request_serializer=inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModel(self, request, context):
        """Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvictModelRegistryEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Session control plane
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capabilities(self, request, context):
        """Introspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=inference__pb2.LoadModelRequest.FromString,
                    response_serializer=inference__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=inference__pb2.UnloadModelRequest.FromString,
                    response_serializer=inference__pb2.UnloadModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=inference__pb2.ListModelsRequest.FromString,
                    response_serializer=inference__pb2.ListModelsResponse.SerializeToString,
            ),
            'ListModelRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelRegistry,
                    request_deserializer=inference__pb2.ListModelRegistryRequest.FromString,
                    response_serializer=inference__pb2.ListModelRegistryResponse.SerializeToString,
            ),
            'EvictModelRegistryEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.EvictModelRegistryEntry,
                    request_deserializer=inference__pb2.EvictModelRegistryRequest.FromString,
                    response_serializer=inference__pb2.EvictModelRegistryResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=inference__pb2.PredictRequest.FromString,
                    response_serializer=inference__pb2.PredictResponse.SerializeToString,
            ),
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=inference__pb2.StreamPredictRequest.FromString,
                    response_serializer=inference__pb2.StreamPredictResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=inference__pb2.OpenSessionRequest.FromString,
                    response_serializer=inference__pb2.OpenSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=inference__pb2.CloseSessionRequest.FromString,
                    response_serializer=inference__pb2.CloseSessionResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=inference__pb2.CancelSessionRequest.FromString,
                    response_serializer=inference__pb2.CancelSessionResponse.SerializeToString,
            ),
            'Capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.Capabilities,
                    request_deserializer=inference__pb2.CapabilitiesRequest.FromString,
                    response_serializer=inference__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inference__pb2.HealthRequest.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/LoadModel',
            inference__pb2.LoadModelRequest.SerializeToString,
            inference__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/UnloadModel',
            inference__pb2.UnloadModelRequest.SerializeToString,
            inference__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/ListModels',
            inference__pb2.ListModelsRequest.SerializeToString,
            inference__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModelRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/ListModelRegistry',
            inference__pb2.ListModelRegistryRequest.SerializeToString,
            inference__pb2.ListModelRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvictModelRegistryEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/EvictModelRegistryEntry',
            inference__pb2.EvictModelRegistryRequest.SerializeToString,
            inference__pb2.EvictModelRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/Predict',
            inference__pb2.PredictRequest.SerializeToString,
            inference__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.InferenceService/StreamPredict',
            inference__pb2.StreamPredictRequest.SerializeToString,
            inference__pb2.StreamPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/OpenSession',
            inference__pb2.OpenSessionRequest.SerializeToString,
            inference__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/CloseSession',
            inference__pb2.CloseSessionRequest.SerializeToString,
            inference__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/CancelSession',
            inference__pb2.CancelSessionRequest.SerializeToString,
            inference__pb2.CancelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/Capabilities',
            inference__pb2.CapabilitiesRequest.SerializeToString,
            inference__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/Health',
            inference__pb2.HealthRequest.SerializeToString,
            inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
